# Generated by Django 3.0.6 on 2020-06-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='promedio',
            new_name='averag',
        ),
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='calificacion1',
            new_name='grade1',
        ),
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='calificacion2',
            new_name='grade2',
        ),
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='calificacion3',
            new_name='grade3',
        ),
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='alumno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listacalificacion',
            old_name='materia',
            new_name='subject',
        ),
    ]
