# Generated by Django 3.0.6 on 2020-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_auto_20200616_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Alumno')),
                ('subject', models.CharField(max_length=50, verbose_name='Materia')),
                ('grade1', models.IntegerField(verbose_name='Calificación 1')),
                ('grade2', models.IntegerField(verbose_name='Calificación 2')),
                ('grade3', models.IntegerField(verbose_name='Calificación 3')),
                ('averag', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Promedio')),
            ],
        ),
        migrations.DeleteModel(
            name='ListaCalificacion',
        ),
    ]
