# Generated by Django 3.0.6 on 2020-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_auto_20200617_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='averag',
            field=models.IntegerField(verbose_name='Promedio'),
        ),
    ]
